/* 
  ============================================================
   Magnitude Analysis
   ============================================================
   Purpose: Analyze the magnitude of business metrics across 
            customers, products, and sales.
   ============================================================ 
*/

-- Magnitude Analysis
-- total customers by country
select 
	country,
	count(customer_key) as customer_per_country
from gold.dim_customers
group by country
order by customer_per_country desc

-- total customers by gender
select 
	gender,
	count(customer_key) as customer_per_gender
from gold.dim_customers
group by gender
order by customer_per_gender desc

-- total products per category
select 
	category,
	count(product_name) as products_per_category
from gold.dim_products
group by category
order by products_per_category desc


--average cost in each category
select 
	category,
	avg(cost) as average_cost_per_category
from gold.dim_products
group by category 
order by average_cost_per_category desc


-- total revenues generated for each category
select 
	p.category,
	sum(sales_amount) as total_revenue_per_category
from gold.fact_sales f
left join gold.dim_products p
on p.product_key= f.product_key
group by p.category
order by total_revenue_per_category desc


-- total revenue generated by each customer
select 
	c.customer_key,
	concat(coalesce(c.first_name,''),' ',coalesce(c.last_name,'')) as full_name,
	sum(f.sales_amount) as revenue_per_customer
from gold.fact_sales as f
left join gold.dim_customers as c
on f.customer_key  = c.customer_key
group by c.customer_key,c.first_name,c.last_name
order by revenue_per_customer desc


-- distribution of sold items accross countries
select 
	c.country,
	sum(f.quantity) as total_sold_items
from gold.fact_sales as f
left join gold.dim_customers as c
on f.customer_key  = c.customer_key
group by c.country
order by total_sold_items desc
